<?php

module_load_include('php','gavias_elements', 'includes/instagram');
function gavias_elements_list_shortcodes(){
  return $shortcodes = array(
    'gsc_accordion',
    'gsc_box_color', 
    //'gsc_box_number',
    //'gsc_box_info',
    //'gsc_box_text',
    'gsc_call_to_action',
    'gsc_chart',
    'gsc_code',
    'gsc_column',
    'gsc_counter',
    'gsc_drupal_block',
    'gsc_heading',
    'gsc_icon_box',
    'gsc_image',
    'gsc_our_team',
    'gsc_pricing_item',
    'gsc_progress',
    'gsc_tabs',
    'gsc_video_box',
    //'gsc_multi_scroll',
    'gsc_gmap',
    'gsc_button',
    'gsc_view',
    'gsc_quote_text',
    //'gsc_work_process',
    'gsc_image_content',
    'gsc_services_carousel',
    //'gsc_our_history',
    'gsc_gallery',
    'gsc_our_partners',
    'gsc_download',
    'gsc_socials',
    'gsc_instagram',
    'gsc_carousel_content'
  );
}

$shortcodes = gavias_elements_list_shortcodes();
foreach( $shortcodes as $sc ){
    if(file_exists(drupal_get_path('module', 'gavias_elements') . '/elements/' . $sc . '.php')){
        $sc_path = drupal_get_path('module', 'gavias_elements') . '/elements/' . $sc . '.php';
        require($sc_path);
        $_class = '\\Drupal\gavias_blockbuilder\shortcodes\\' . $sc;
        if( class_exists($_class) ){
          $s = new $_class;
          if(method_exists($s, 'load_shortcode') && function_exists('add_shortcode')){
                $s->load_shortcode();
            }
        }
    }
}  

function gavias_elements_update_projects_alter(&$projects){
   unset($projects['gavias_elements']);
}

if(!function_exists('gavias_print_animate_aos')){
    function gavias_print_animate_aos($animate=''){
        if($animate){
            return 'data-aos="'.$animate.'"';
        }
        return '';
    }
}